# Generated by Django 3.0.5 on 2021-01-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="operating_system",
            field=models.CharField(default="", max_length=50),
        ),
    ]
