# Generated by Django 3.0.5 on 2021-01-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210107_2209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="registered_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
