# Generated by Django 3.0.5 on 2021-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20210108_1732"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "Device", "verbose_name_plural": "Devices"},
        ),
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(
                help_text="A unique ID to identify each device",
                max_length=40,
                unique=True,
                verbose_name="Device ID",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="location",
            field=models.CharField(
                help_text="The location of the device (city/country)",
                max_length=100,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="operating_system",
            field=models.CharField(
                help_text="The operating system name, edition and architecture",
                max_length=50,
                verbose_name="Operating System",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="registered_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time the device was registered",
                verbose_name="Registered at",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="version",
            field=models.CharField(
                help_text="The pyVoice version installed",
                max_length=10,
                verbose_name="Version",
            ),
        ),
    ]
