"""
Django settings for device_api project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import dotenv

# load env variables
dotenv.load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')


if DEBUG:
    SECRET_KEY = os.getenv('SECRET_KEY')
    ALLOWED_HOSTS = []
else:
    SECRET_KEY = os.environ.get('SECRET_KEY')
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(' ')

# Application definition








# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators


if DEBUG:
    
else:
    


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/




# Rest Framework setup




# CORS

CORS_ALLOW_ALL_ORIGINS = True


# API Key
# API_KEY_CUSTOM_HEADER = 'HTTP_PV_API_KEY'PI'