name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # allow for manual workflow running
  workflow_dispatch:

jobs:
  # checkout the code, install dependencies and test the application
  test:
    name: Test the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt

      - name: Run Django tests
        run: |
          python manage.py test api --settings=device_api.settings.testing -v 2

  # deploys to Heroku
  deploy:
    name: Deploy on Heroku (production)
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  # notify the build and deploy status using PushBullet
  notify:
    name: Notify status
    needs: ['test', 'deploy']
    runs-on: ubuntu-latest
    steps:
      - name: Notify build succeed
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: '[Device API] Build and deploy completed'
          PB_TEXT: 'Device API has been tested and deployed successfully!'
