name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # allow for manual workflow running
  workflow_dispatch:

jobs:
  # checkout the code, install dependencies and test the application
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-path: ~/.virtualenvs
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install dependencies
        run: |
          poetry install

      - name: Run Django tests
        run: |
          poetry run python manage.py test api --settings=device_api.settings.testing -v 2

  # notify the tests are OK using PushBullet
  notify:
    name: Notify
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - name: Notify tests OK
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: '[Device API] Tests OK'
          PB_TEXT: 'Device API has been tested and was sent to Heroku for deploy on production'
