name: Test the application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # checkout the code, install dependencies and test the application
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
      - name: Run Django tests
        run: |
          python manage.py test api --settings=device_api.settings.testing -v 2

  # deploys to Heroku
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to Heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify build succeed
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: '[Device API] Build and deploy completed'
          PB_TEXT: 'Device API has been tested and deployed successfully!'
